### ISSUE TITLE
managing users problems and errors

### ISSUE THREAD

**Issue by ghost** [nasirkhan/laravel-starter#118]
- when show,editing,changing password etc from a user from admin panel

ErrorException thrown with message "compact(): Undefined variable: users"

Stacktrace:
#66 ErrorException in /Applications/MAMP/htdocs/LARAVEL/laravel-starter/app/Http/Controllers/Backend/UserController.php:528
#65 compact in /Applications/MAMP/htdocs/LARAVEL/laravel-starter/app/Http/Controllers/Backend/UserController.php:528
#64 App\Http\Controllers\Backend\UserController:edit in /Applications/MAMP/htdocs/LARAVEL/laravel-starter/vendor/laravel/framework/src/Illuminate/Routing/Controller.php:54
#63 call_user_func_array in /Applications/MAMP/htdocs/LARAVEL/laravel-starter/vendor/laravel/framework/src/Illuminate/Routing/Controller.php:54
#62 Illuminate\Routing\Controller:callAction in /Applications/MAMP/htdocs/LARAVEL/laravel-starter/app/Authorizable.php:33
#61 App\Http\Controllers\Backend\UserController:callAction in /Applications/MAMP/htdocs/LARAVEL/laravel-starter/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php:45
#60 Illuminate\Routing\ControllerDispatcher:dispatch in /Applications/MAMP/htdocs/LARAVEL/laravel-starter/vendor/laravel/framework/src/Illuminate/Routing/Route.php:219
#59 Illuminate\Routing\Route:runController in /Applications/MAMP/htdocs/LARAVEL/laravel-starter/vendor/laravel/framework/src/Illuminate/Routing/Route.php:176
#58 Illuminate\Routing\Route:run in /Applications/MAMP/htdocs/LARAVEL/laravel-starter/vendor/laravel/framework/src/Illuminate/Routing/Router.php:682
#57 Illuminate\Routing\Router:Illuminate\Routing\{closure} in /Applications/MAMP/htdocs/LARAVEL/laravel-starter/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:30
#56 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /Applications/MAMP/htdocs/LARAVEL/laravel-starter/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authorize.php:45
#55 Illuminate\Auth\Middleware\Authorize:handle in /Applications/MAMP/htdocs/LARAVEL/laravel-starter/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:151
#54 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /Applications/MAMP/htdocs/LARAVEL/laravel-starter/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#53 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /Applications/MAMP/htdocs/LARAVEL/laravel-starter/app/Http/Middleware/GenerateMenus.php:201
#52 App\Http\Middleware\GenerateMenus:handle in /Applications/MAMP/htdocs/LARAVEL/laravel-starter/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:151
#51 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /Applications/MAMP/htdocs/LARAVEL/laravel-starter/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#50 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /Applications/MAMP/htdocs/LARAVEL/laravel-starter/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php:41
#49 Illuminate\Routing\Middleware\SubstituteBindings:handle in /Applications/MAMP/htdocs/LARAVEL/laravel-starter/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:151
#48 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /Applications/MAMP/htdocs/LARAVEL/laravel-starter/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#47 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /Applications/MAMP/htdocs/LARAVEL/laravel-starter/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authenticate.php:43
#46 Illuminate\Auth\Middleware\Authenticate:handle in /Applications/MAMP/htdocs/LARAVEL/laravel-starter/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:151
#45 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /Applications/MAMP/htdocs/LARAVEL/laravel-starter/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#44 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /Applications/MAMP/htdocs/LARAVEL/laravel-starter/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php:75
#43 Illuminate\Foundation\Http\Middleware\VerifyCsrfToken:handle in /Applications/MAMP/htdocs/LARAVEL/laravel-starter/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:151
#42 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /Applications/MAMP/htdocs/LARAVEL/laravel-starter/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#41 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /Applications/MAMP/htdocs/LARAVEL/laravel-starter/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php:49
#40 Illuminate\View\Middleware\ShareErrorsFromSession:handle in /Applications/MAMP/htdocs/LARAVEL/laravel-starter/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:151
#39 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /Applications/MAMP/htdocs/LARAVEL/laravel-starter/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#38 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /Applications/MAMP/htdocs/LARAVEL/laravel-starter/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php:63
#37 Illuminate\Session\Middleware\StartSession:handle in /Applications/MAMP/htdocs/LARAVEL/laravel-starter/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:151
#36 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /Applications/MAMP/htdocs/LARAVEL/laravel-starter/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#35 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /Applications/MAMP/htdocs/LARAVEL/laravel-starter/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php:37
#34 Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse:handle in /Applications/MAMP/htdocs/LARAVEL/laravel-starter/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:151
#33 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /Applications/MAMP/htdocs/LARAVEL/laravel-starter/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#32 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /Applications/MAMP/htdocs/LARAVEL/laravel-starter/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php:66
#31 Illuminate\Cookie\Middleware\EncryptCookies:handle in /Applications/MAMP/htdocs/LARAVEL/laravel-starter/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:151
#30 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /Applications/MAMP/htdocs/LARAVEL/laravel-starter/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#29 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /Applications/MAMP/htdocs/LARAVEL/laravel-starter/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:104
#28 Illuminate\Pipeline\Pipeline:then in /Applications/MAMP/htdocs/LARAVEL/laravel-starter/vendor/laravel/framework/src/Illuminate/Routing/Router.php:684
#27 Illuminate\Routing\Router:runRouteWithinStack in /Applications/MAMP/htdocs/LARAVEL/laravel-starter/vendor/laravel/framework/src/Illuminate/Routing/Router.php:659
#26 Illuminate\Routing\Router:runRoute in /Applications/MAMP/htdocs/LARAVEL/laravel-starter/vendor/laravel/framework/src/Illuminate/Routing/Router.php:625
#25 Illuminate\Routing\Router:dispatchToRoute in /Applications/MAMP/htdocs/LARAVEL/laravel-starter/vendor/laravel/framework/src/Illuminate/Routing/Router.php:614
#24 Illuminate\Routing\Router:dispatch in /Applications/MAMP/htdocs/LARAVEL/laravel-starter/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:176
#23 Illuminate\Foundation\Http\Kernel:Illuminate\Foundation\Http\{closure} in /Applications/MAMP/htdocs/LARAVEL/laravel-starter/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:30
#22 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /Applications/MAMP/htdocs/LARAVEL/laravel-starter/vendor/barryvdh/laravel-debugbar/src/Middleware/InjectDebugbar.php:65
#21 Barryvdh\Debugbar\Middleware\InjectDebugbar:handle in /Applications/MAMP/htdocs/LARAVEL/laravel-starter/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:151
#20 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /Applications/MAMP/htdocs/LARAVEL/laravel-starter/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#19 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /Applications/MAMP/htdocs/LARAVEL/laravel-starter/vendor/fideloper/proxy/src/TrustProxies.php:57
#18 Fideloper\Proxy\TrustProxies:handle in /Applications/MAMP/htdocs/LARAVEL/laravel-starter/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:151
#17 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /Applications/MAMP/htdocs/LARAVEL/laravel-starter/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#16 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /Applications/MAMP/htdocs/LARAVEL/laravel-starter/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php:31
#15 Illuminate\Foundation\Http\Middleware\TransformsRequest:handle in /Applications/MAMP/htdocs/LARAVEL/laravel-starter/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:151
#14 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /Applications/MAMP/htdocs/LARAVEL/laravel-starter/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#13 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /Applications/MAMP/htdocs/LARAVEL/laravel-starter/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php:31
#12 Illuminate\Foundation\Http\Middleware\TransformsRequest:handle in /Applications/MAMP/htdocs/LARAVEL/laravel-starter/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:151
#11 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /Applications/MAMP/htdocs/LARAVEL/laravel-starter/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#10 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /Applications/MAMP/htdocs/LARAVEL/laravel-starter/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php:27
#9 Illuminate\Foundation\Http\Middleware\ValidatePostSize:handle in /Applications/MAMP/htdocs/LARAVEL/laravel-starter/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:151
#8 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /Applications/MAMP/htdocs/LARAVEL/laravel-starter/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#7 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /Applications/MAMP/htdocs/LARAVEL/laravel-starter/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php:62
#6 Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode:handle in /Applications/MAMP/htdocs/LARAVEL/laravel-starter/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:151
#5 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /Applications/MAMP/htdocs/LARAVEL/laravel-starter/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#4 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /Applications/MAMP/htdocs/LARAVEL/laravel-starter/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:104
#3 Illuminate\Pipeline\Pipeline:then in /Applications/MAMP/htdocs/LARAVEL/laravel-starter/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:151
#2 Illuminate\Foundation\Http\Kernel:sendRequestThroughRouter in /Applications/MAMP/htdocs/LARAVEL/laravel-starter/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:116
#1 Illuminate\Foundation\Http\Kernel:handle in /Applications/MAMP/htdocs/LARAVEL/laravel-starter/public/index.php:53
#0 require_once in /Applications/MAMP/htdocs/LARAVEL/laravel-starter/server.php:19

 

- accessing a profile of a registered user from the admin panel:

ErrorException (E_ERROR)
Trying to get property 'name' of non-object (View: /Applications/MAMP/htdocs/LARAVEL/laravel-starter/resources/views/backend/users/profile.blade.php)

**Comment by nasirkhan** [comment]
Resolved in latest version
