### ISSUE TITLE
laravel file manager use for image gallery by id and module

### ISSUE THREAD

**Issue by stormtr** [nasirkhan/laravel-starter#150]
Dear Nasir,

i need to integrate this LFM to your Article section there is only one image i need to make gallery on this area can you check image for this. How can i integrate it or will i use other codes.. I can make with manually but i wat to use this script if possible . what you think?

![image](https://user-images.githubusercontent.com/7202660/61642416-827a1480-aca9-11e9-8739-b060db5bb7e3.png)

**Comment by stormtr** [comment]
for example would save image like
http://example.com/uploads/product/1/image_name.jpg

is there a way for this with your script LFM.

**Comment by nasirkhan** [comment]
LFM supports multiple file upload and selecting at once. Photo Gallery is not implemented in this project yet. So if you want to use gallery with this starter, you have implement by yourself.
