### ISSUE TITLE
Create module make problem

### ISSUE THREAD

**Issue by Hyperizon** [nasirkhan/laravel-starter#151]
Dear Nasir,

Cannot create some files.
Files that do not occur: Console, Database (Migrations and Factories), Entities, Http(Backend and Frontend need to build into), Middleware, Requests, Views

I wonder why there's no scaffold in the Asgard?

![image](https://user-images.githubusercontent.com/16267822/61771753-4b1a7d80-adf9-11e9-9e0a-ebfd0c7dc9a8.png)

![image](https://user-images.githubusercontent.com/16267822/61771320-37224c00-adf8-11e9-9edf-2244d9a1e96f.png)

**Comment by nasirkhan** [comment]
You can control which files and directories will be published with a new module and which will not. You need to update the `config/module.php` (https://github.com/nasirkhan/laravel-starter/blob/master/config/modules.php#L27) and update as per your need. 

You can copy all the files from `/vendor/nwidart/laravel-modules/src/Commands/stubs` and place those somewhere in your project and reference that on the `config/module.php`.

I template module will be added to this repo soon. As it is not available yet, you can try yourself. Please let me know your progress on this.

**Comment by Hyperizon** [comment]
Ok, thanks. I will be try.
