### ISSUE TITLE
ckeditor Content view error on forms

### ISSUE THREAD

**Issue by stormtr** [nasirkhan/laravel-starter#152]
![image](https://user-images.githubusercontent.com/7202660/62359622-db567200-b51f-11e9-8c79-7160294a361a.png)
![image](https://user-images.githubusercontent.com/7202660/62359644-e7423400-b51f-11e9-8555-16ad2a795823.png)

dear in article 
there is content and featuredimage but ckeditor has a problem i think you need to check.

thanks

**Comment by nasirkhan** [comment]
Can you please check once again? i use this panel regularly and it works for me. But it takes a while to load the ckeditor and show the contents on the panel. 


![Screenshot_2019-08-02 Edit Posts Awesome Laravel Awesome Laravel](https://user-images.githubusercontent.com/396987/62366360-76fbd880-b548-11e9-958a-50c588289309.png)

**Comment by stormtr** [comment]
i found the problem please update public\plugins\ckeditor to teh latest one then it will work

**Comment by stormtr** [comment]
i found the problem please update public\plugins\ckeditor to teh latest one then it will work
