### ISSUE TITLE
hi setting-fields

### ISSUE THREAD

**Issue by stormtr** [nasirkhan/laravel-starter#154]
we used a below section to make checkbox but its not working can you check it. is there any problem

```
<input name="{{ $field['name'] }}" value="1" type="checkbox" @if(old($field['name'], setting($field['name']))) checked="checked" @endif >

        'elements' => [
            [
                'type'  => 'checkbox',
                'data'  => 'int',
                'name'  => 'mac',
                'label' => 'Mac Control',
                'rules' => '',
                'class' => 'switch-input',
                'value' => '1',
            ],
```

**Comment by stormtr** [comment]
for example i need to make here true / false

**Comment by stormtr** [comment]
for checkbox use like below its working:

            [
                'type'  => 'checkbox', // input fields type
                'data'  => 'boolean', // data type, string, int, boolean
                'name'  => 'Name', // unique name for field
                'label' => 'Name Label ', // you know what label it is
                'rules' => '', // validation rule of laravel
                'class' => 'form-control switch-input', // any class for input
                'value' => '1', // default value if you want
            ],


<div class="form-group {{ $errors->has($field['name']) ? ' has-error' : '' }}">
    <label for="{{ $field['name'] }}"> <strong>{{ $field['label'] }}</strong> ({{ $field['name'] }})</label>
    <div class="checkbox">
        <label class="switch switch-label switch-outline-primary-alt">
            {{Form::hidden($field['name'],0, null,null)}}
            {{Form::checkbox($field['name'], null, old($field['name'], setting($field['name'])), array('class'=> $field['class']))}}
            <span class="switch-slider" data-checked="1" data-unchecked="0"></span>
        </label>
        @if ($errors->has($field['name'])) <small class="invalid-feedback">{{ $errors->first($field['name']) }}</small> @endif
    </div>
</div>

**Comment by nasirkhan** [comment]
Thanks for your support. Feel free to send pull requests. This project is
not complete and there are always room for improvements.
