### ISSUE TITLE
Settings checkbox problem

### ISSUE THREAD

**Issue by Hyperizon** [nasirkhan/laravel-starter#159]
Hi Nasir, 

Checkbox is not saved in settings.

how to fix ?

checkbox.blade.php = 
![image](https://user-images.githubusercontent.com/16267822/66316494-730d7d80-e920-11e9-9dc2-b238c043cd43.png)

settings_fields = 
![image](https://user-images.githubusercontent.com/16267822/66316532-83255d00-e920-11e9-9b7f-4ddc8ffe54dd.png)

**Comment by nasirkhan** [comment]
Let me check the issue and will try to post to fix within this week. 

If you already created the solution, please submit a PR.

**Comment by nasirkhan** [comment]
Fixed the issue.

here is an example of checklist, 

```
[
    'type'  => 'checkbox', // input fields type
    'data'  => 'text', // data type, string, int, boolean
    'name'  => 'show_copyright', // unique name for field
    'label' => 'Show Copyright', // you know what label it is
    'rules' => '', // validation rule of laravel
    'class' => '', // any class for input
    'value' => '1', // default value if you want
],
```

you can check the commit details at https://github.com/nasirkhan/laravel-starter/commit/bcb20a13547baa6ad4f9d0774b065083a7ceaf68
