### ISSUE TITLE
Migrate problem

### ISSUE THREAD

**Issue by Hyperizon** [nasirkhan/laravel-starter#179]
Migratings not working
code: php artisan migrate
When I write the above code, it does not migrate all the tables.
![image](https://user-images.githubusercontent.com/16267822/68190745-076e0d00-ffbf-11e9-8f78-61414d89e088.png)

**Comment by nasirkhan** [comment]
Could you please run the following command and try the migration again? I hope this will solve your issue and It will be fixed on the next release. 

```
php artisan module:v6:migrate
```

**Comment by Hyperizon** [comment]
Migrate problem solved

php artisan module:seed function gives the below error.
![image](https://user-images.githubusercontent.com/16267822/68198525-473bf100-ffcd-11e9-8eea-ded9a34ccfb0.png)

**Comment by K0styan** [comment]
Migration is not working.
![image](https://user-images.githubusercontent.com/15695694/74682315-c0ef9780-51d6-11ea-832b-cc7c204046eb.png)

**Comment by nasirkhan** [comment]
new version released and it solves the mentioned issue.
