### ISSUE TITLE
comment update return 404

### ISSUE THREAD

**Issue by stormtr** [nasirkhan/laravel-starter#182]
when try to make update on comment it return 404

**Comment by stormtr** [comment]
its about encode

**Comment by MouadBH** [comment]
hi @stormtr, I face the same issue, how you fixed it?

**Comment by nasirkhan** [comment]
from where you are getting this issue?

**Comment by MouadBH** [comment]
when i try to update comment.
![image](https://user-images.githubusercontent.com/28781942/85148247-d38ee180-b247-11ea-9633-e459f4d5d471.png)

**Comment by stormtr** [comment]
> when i try to update comment.
> ![image](https://user-images.githubusercontent.com/28781942/85148247-d38ee180-b247-11ea-9633-e459f4d5d471.png)

Please check link /1 must encode

**Comment by nasirkhan** [comment]
Made some changes, can you please clone the application again and confirm if it is resolved. thanks

**Comment by MouadBH** [comment]
works fine thank you guys.

**Comment by nasirkhan** [comment]
thanks
