### ISSUE TITLE
Login page not working

### ISSUE THREAD

**Issue by Hyperizon** [nasirkhan/laravel-starter#184]
Login was broken with the last update.

![image](https://user-images.githubusercontent.com/16267822/71176970-00077800-227c-11ea-83ba-aa17b7e194b0.png)

**Comment by nasirkhan** [comment]
I am sorry that you had to face this issue. I was updating the user auth code and you have to wait till next week to make it a finished product.

**Comment by CryptVenture** [comment]
Any ideas when this might be corrected?

**Comment by JuyelRana** [comment]
@nasirkhan Have you updated your code?

**Comment by nasirkhan** [comment]
I started to work on the project and i hope i will be able to make it
workable within this week.
Thank you for your interest. i will update this issue while i am done.

**Comment by JuyelRana** [comment]
@nasirkhan I have already used this template for more than five projects and it's saving my huge time. Thanks a lot for giving this wonderful ready project free.

**Comment by ffaaddiill** [comment]
could i clone new one ? because i found the same issue. thankyou for this template

**Comment by ffaaddiill** [comment]
@nasirkhan hi, i tried to repair the login page

![laravelstarter-nasirkhan](https://user-images.githubusercontent.com/4361303/75587969-4104df80-5aaa-11ea-8cf1-752733b5f2c7.png)

it seems you deleted the LoginController source code, the showLoginForm() function was not loaded, the showLoginForm() function will return the blade file of corrected login page on the auth1 folder, something like this:

![laravelstarter-nasirkhan-LoginController](https://user-images.githubusercontent.com/4361303/75588432-3bf46000-5aab-11ea-9a49-457540b99d56.png)

but i'm just testing, i've not already solved all. please share the source code here if one of us done with this. thankyou :)

**Comment by nasirkhan** [comment]
thanks for looking into this. I will try to push an update by end of the
day.

--
*Nasir Khan Saikat*
www.nasirkhn.com

**Comment by ffaaddiill** [comment]
thankyou, we are waiting for update from you. God bless you

**Comment by nasirkhan** [comment]
new version released and it solves the mentioned issue.
