### ISSUE TITLE
session problem with new project

### ISSUE THREAD

**Issue by stormtr** [nasirkhan/laravel-starter#190]
hi Nasir there is a problem on Session with this project with new Laravel i download and made test with your project and for example on main page if you make refresh sometimes system is reading REGISTER are sometimes not.

**Comment by nasirkhan** [comment]
Thank you for using this project.

Can you please describe the issue in more elaborated way, so that i can
reproduce on my machine?

--
*Nasir Khan Saikat*
www.nasirkhn.com

**Comment by stormtr** [comment]
Hi for example 

on main page 5-10 times click F5 (refresh) and the register is removing and coming

![image](https://user-images.githubusercontent.com/7202660/76606666-bac5b000-6523-11ea-89c5-f380b59034ec.png)

**Comment by nasirkhan** [comment]
You have to add an environment variable `USER_REGISTRATION=true` . If there is no variable registration related all the features will be disabled. 

https://github.com/nasirkhan/laravel-starter/blob/master/.env.example#L7

**Comment by stormtr** [comment]
there is USER_REGISTRATION=true. But i think there is a problem with integration laravel 7

**Comment by stormtr** [comment]
for example in your  project on main page frontend click F5 refreh page double click (fastly) and the register will remove it can be from the Session.

**Comment by nasirkhan** [comment]
I am sorry that you are facing the issue.

I tried to refresh the page multiple times and fast enough. But could not
reproduce the problem. Are you trying on a fresh installation, if not can
please do so and try again from a different browser?

Registration button is enabled and disabled from the blade view and session
is not involved here. enable disable registration view and route is not
within the Laravel 7, i added this on the project.

--
*Nasir Khan Saikat*
www.nasirkhn.com

**Comment by nasirkhan** [comment]
Does the issue exists? 
I am closing as it is inactive for a week. Please reopen if necessary.

**Comment by stormtr** [comment]
Dear Nasir
i solved the problem , problem is from the USER_REGISTRATION codes in helper. Because there is a code if true user_registration is true tehre is a problem. if removed this everything work fine. so i think here must check only only the true or false but firstly you are making it false and if refresh fastly system is making it directly false

    function user_registration()
    {
    ###     **$user_registration = false;**

        if (env('USER_REGISTRATION') == 'true') {
            $user_registration = true;
        }

        return $user_registration;
    }

**Comment by nasirkhan** [comment]
Thanks for your feedback and i am glad that project is working for you now. 

On a previous comment i mentioned that you have to add a new environment variable `USER_REGISTRATION=true` to enable the registration. As it was not required in the previous version so i can not sure if the previous users will follow the changes. So this `user_registration()` helper function came in. Which assumes that registration is disabled and if enabled from the .env file registration will work again. 

if i remove the `$user_registration = false;` line and do not have the `USER_REGISTRATION` in `.env` then application will through an exception. You can try yourself. 

on the `user_registration()` function, first i am setting the $user_registration as false, and if i found true in .env then $user_registration became true else it will remain false. There will be other ways to solve this problem but it works. 

I hope this explanation helps you to understand the reason behind this code.
