### ISSUE TITLE
multi language

### ISSUE THREAD

**Issue by stormtr** [nasirkhan/laravel-starter#196]
dear Nashir do you think to integrate multilanguage package to the system?

**Comment by nasirkhan** [comment]
I have plans to do so, but could not manage enough time to concentrate there yet. 

Some of the parts of the application uses the laravel default localization files but not all.

If you are interested you can send pull requests.

**Comment by ghahabib** [comment]
Hello
And thank you for this wonderful work,
Is it possible to integrate multilanguage package (RTL) to the system, especially the frontend?
thanks.

**Comment by nasirkhan** [comment]
@ghahabib 

I am glad that you found this project useful. 

I am sorry that implementing RTL version would be a huge task for me and I can not read any RTL language. If someone can submit any pull request then i can merge that. 

On the other hand, the themes used in backend and frontend both supports the RTL.

**Comment by ghahabib** [comment]
Thank you again
I understand this big job.
I hope you are in your future plan.
There is a very beautiful example of a language merge in this link
https://demo.laravel-boilerplate.com/login
But I do not have enough experience to wear this
Thank you.

**Comment by nasirkhan** [comment]
Language Switcher and multilingual feature added in v7.5.0 (https://github.com/nasirkhan/laravel-starter/releases/tag/v7.5.0)

Whole application is not translatable yet, but will be so within a very short time.

**Comment by ghahabib** [comment]
Thank you so much
Really a great thing.

**Comment by stormtr** [comment]
perfect so we need to integrate database language support and this project also needs product gallery like spatie medialibrary..

**Comment by nasirkhan** [comment]
@stormtr  Can you please tell mere details about the Database language support and Product gallery? Spatie Medialibrary package is already being used here. did you installed the latest version of this laravel-starter?

**Comment by stormtr** [comment]
Yes Nasirkhan i installed already latest version and for example in Article section there is a featured_image but i think there might be multi images for example 1 article can be 10 images to show. but at the moment oşly 1 image can add..
maybe we need a module called gallery..

For the language in article database migrating file must have      $table->string('lang', 2)->default('en');
and in Form section we need to pass lang code with hidden object (will get from session) to this column.

**Comment by nasirkhan** [comment]
@stormtr I thought featured image should be one single image. You could add other images into the content area. 

A language column can be added to posts table, but on that case we need to add this column on each table. Do you think it would be a good decision to the column on this generic project?

**Comment by stormtr** [comment]
content areas images are not suitable for example sliders etc. content are like a book nut images must have a dattables to use it everywhere, forexample if you want to make advertise but you can not use slider images, sample as below.
http://www.rangs.com.bd/product/product_details/497

![image](https://user-images.githubusercontent.com/7202660/88795766-39f11300-d1a9-11ea-9e77-bf4c3befe231.png)

so i think every project must have a gallery for products, articles, menu

**Comment by nasirkhan** [comment]
Thanks for your thoughts.

It is true that the featured image is not suitable for slides and so.
Because the intent of posts module is not serve all purposes. The only
objective is to write articles, something similar as Posts in WordPress or
Articles in Joomla CMS. But you can extend it as per your need.

The example you share is a product page. A product have many more
attributes than a post. So I would not use Post/Article module for product.
Rather I will create a new module, may be by extending the posts.

But again if you are confident then please submit a pull request for this
feature.

**Comment by stormtr** [comment]
i made a simple slider and it can add to other modules only must add to action_column you can make it better and everybody can use it.
add module then run  php artisan module:publish
[Gallery.zip](https://github.com/nasirkhan/laravel-starter/files/4995031/Gallery.zip)

**Comment by stormtr** [comment]
dear Nasir i do not know how will be pull request can be problem so i add it here by zip file.

**Comment by stormtr** [comment]
also frontend menu organiser.

[Menu.zip](https://github.com/nasirkhan/laravel-starter/files/4995048/Menu.zip)

**Comment by stormtr** [comment]
for working teams for company.

[Team.zip](https://github.com/nasirkhan/laravel-starter/files/4995049/Team.zip)

**Comment by stormtr** [comment]
if you find a time please check and add it to project with controlled and add new featuıred

**Comment by stormtr** [comment]
and added language swither to frontend

[header.blade.zip](https://github.com/nasirkhan/laravel-starter/files/4995078/header.blade.zip)

**Comment by stormtr** [comment]
for svg flags etc you can add 
[svg.zip](https://github.com/nasirkhan/laravel-starter/files/4995084/svg.zip)
 /public

**Comment by nasirkhan** [comment]
Please fork this project or use it as template to create a repo under under your account. Then add these files, it will be easier to check then.

I did not add anything to frontend as it may be used differently by different person. 

The icon set used in backend have flags, i do not like to show flags this was, but can easily be added.

I will check the Gallery and Team module. thanks for sharing. 

I am closing this issue, as the initial issue was resolved. Please create new issue for discussing other topics.
