### ISSUE TITLE
problem on logs

### ISSUE THREAD

**Issue by stormtr** [nasirkhan/laravel-starter#197]
![image](https://user-images.githubusercontent.com/7202660/82730332-84689600-9d07-11ea-99f1-de44f8714f2e.png)

there is problem on logs .

**Comment by nasirkhan** [comment]
Can you please let me know some more details about the issue? like the version of your PHP and did you updated the laravel or you just got this issue right after installing the application?

**Comment by nasirkhan** [comment]
As i could not reproduce the issue, i am closing it. Please reopen if necessary.

**Comment by stormtr** [comment]
dear nashir
php version
HP 7.4.3 (cli) (built: Feb 23 2020 07:24:28) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.3, Copyright (c), by Zend Technologies

**Comment by nasirkhan** [comment]
I pushed a new patch. can you please et me know if it is working as expected.

**Comment by stormtr** [comment]
checking with 7.4.3  then inform you

**Comment by stormtr** [comment]
hi nasir
now its ok logs are working with latest php version

**Comment by nasirkhan** [comment]
thank.
I am really happy that this project helps you.

--
*Nasir Khan Saikat*
www.nasirkhn.com
