### ISSUE TITLE
Call to undefined function App\Http\Controllers\Backend\array_add() 

### ISSUE THREAD

**Issue by KatanaWinter** [nasirkhan/laravel-starter#198]
On User create
Its outdated and should be replaced with Arr:add

love your package

https://laravel.com/docs/7.x/helpers#method-array-add

**Comment by nasirkhan** [comment]
Thanks for finding the issue. I will update that and check other similar
issues.

You may also submit pull requests to improve the project.


--
*Nasir Khan Saikat*
www.nasirkhn.com
