### ISSUE TITLE
The use statement with non-compound name 'Auth' has no effect

### ISSUE THREAD

**Issue by zmutclik** [nasirkhan/laravel-starter#204]
`root@550dfcc993b8:/var/www/html# composer install      
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Nothing to install or update
Package jeremeamia/superclosure is abandoned, you should avoid using it. Use opis/closure instead.
Generating optimized autoload files
```
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
Script Illuminate\Foundation\ComposerScripts::postAutoloadDump handling the post-autoload-dump event terminated with an exception

                                                                 
  [ErrorException]                                               
  The use statement with non-compound name 'Auth' has no effect 
``` 
                                                                 

install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--no-suggest] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--ignore-platform-reqs] [--] [<packages>]...

root@550dfcc993b8:/var/www/html# 
`

**Comment by nasirkhan** [comment]
Thank you for mentioning the issue. It  is resolved now.
