### ISSUE TITLE
how to delete permission

### ISSUE THREAD

**Issue by Hyperizon** [nasirkhan/laravel-starter#230]
Hi Nasir,

I accidentally opened some privileges, how can I destroy them?
![image](https://user-images.githubusercontent.com/16267822/96572322-5e0a4f00-12d5-11eb-9425-c1b99f031cb9.png)

**Comment by Hyperizon** [comment]
I deleted manually from the permission table in the database, I could not find another deletion way

**Comment by nasirkhan** [comment]
sorry that there is ready way to delete permissions. i also checked the permissions package doc and there is none (https://spatie.be/docs/laravel-permission/v3/basic-usage/artisan)

deleting from database might be ok, as permissions can be integrated deeply into the code easy delete can cause issue sometimes. that might be the reason of not having it. 

thanks for using this project.
