### ISSUE TITLE
malformed http_proxy url

### ISSUE THREAD

**Issue by mehran80** [nasirkhan/laravel-starter#245]
i am facing this issue using your laravel-starter. can you help me to solve this issue

**Comment by nasirkhan** [comment]
Can you please write a little more details about the issue. I also need to know the steps to reproduce this issue.

**Comment by mehran80** [comment]
when i run composer install command this issue occur

  Failed to download league/mime-type-detection from dist: Unable to use a proxy: malformed http_proxy url
   Now trying to download from source
and repeated again and again
i attached screenshot

![Capture_Fotor](https://user-images.githubusercontent.com/78439791/106780407-c7865180-6669-11eb-81ee-ef6a5a896a4f.jpg)

**Comment by nasirkhan** [comment]
Did you try `composer update`?

--
*Nasir Khan Saikat*
www.nasirkhn.com

**Comment by mehran80** [comment]
Yes

**Comment by nasirkhan** [comment]
I just installed the project and it installed without showing any error. 

are you using composer 1? can you try to update composer to v2 and try again?

**Comment by mehran80** [comment]
i updated composer to v2 and result is same also check version
 Composer version 2.0.9 2021-01-27 16:09:27
