### ISSUE TITLE
app name

### ISSUE THREAD

**Issue by HR1991** [nasirkhan/laravel-starter#246]
Hi 
when i change app name in settings it doesnt change but other fields change.
also when i press save button in settings the successfully message doesnt show

**Comment by nasirkhan** [comment]
Actually there are two different ways to set and use App Name and you can use either of these. 
1. `app_name()` - it is a helper function uses the `.env` file value via `config`
2. `{{ setting('app_name') }}` or `{!! setting('app_name') !!}` - this uses the value from the settings page
