### ISSUE TITLE
How do I create crud operation from my existing table

### ISSUE THREAD

**Issue by UmairVarin** [nasirkhan/laravel-starter#254]
Hello, I need to create another modules by keep using (laravel-starter), so when I see code for user model, I am shocked, because too much files there for just one User Model (backend, frontend also), so please tell me the command for another models.

**Comment by nasirkhan** [comment]
I am using [laravel module](https://github.com/nWidart/laravel-modules) package to build and manage modules. But my code structure is a little different than the laravel-module. Currently I am working on to build new package which will be used to manage the modules of the laravel-starter module. By this time you can copy an another module like `Tag` module and rename the necessary file and other settings.
