### ISSUE TITLE
New Module Manager/ Generator

### ISSUE THREAD

**Issue by nasirkhan** [nasirkhan/laravel-starter#268]
Create a new package to manage the modules. This package will be used to create new modules and add new components into the module.

**Comment by febrianmosii** [comment]
Hello, thank you nasirkhan, this feature would be good.

**Comment by bepehr** [comment]
+1

**Comment by KriacoesMobile** [comment]
+1👍🏾

**Comment by mrqaidi** [comment]
+1

**Comment by azadshaikh** [comment]
No progress on this?

**Comment by nasirkhan** [comment]
Install the package https://github.com/nasirkhan/module-manager and this will help you to generate new modules. New and existing projects can install this package and get benefited from it.
