### ISSUE TITLE
How put translate files in the project

### ISSUE THREAD

**Issue by mateuslecchi** [nasirkhan/laravel-starter#278]
Hi, I recently started using the project for another in the place that I work.
I want to know how can add the files of the translation to Brazilian Portuguese in the project to future send a PR.

**Comment by nasirkhan** [comment]
Thank you for using the project. 

There are a number of localization files used in different parts of the project. This project also comes with a language switcher as well. 

For translation/ language files it follows the recommendations from Laravel. You can add you language files in  `resources/lang` directory. There are two approaches (https://laravel.com/docs/8.x/localization), one is to create a directory by the 2 character language code and add strings as an array or you can use a JSON file to add the translation. both of these examples are placed in the mentioned directory. 

One thing you keep in mind that it is not 100% enabled for localization. I could not manage enough time to do so, but I will welcome new PR to make the localization coverage 100%.

**Comment by mateuslecchi** [comment]
Thk for the atention, 

I will try to make a full translation on my free time.

**Comment by nasirkhan** [comment]
you are most welsome. You may also update the parts which are not currently covered and submit a PR.
