### ISSUE TITLE
Error with composer install command

### ISSUE THREAD

**Issue by mohamedmehdigara** [nasirkhan/laravel-starter#279]

**Comment by mikield** [comment]
Honestly this is not related to a project, your composer output says that "Your local server doest not match project requirements".

As you can see the first problem says that your PHP version is not matching required one.
```
Problem 1
- Root composer.json requires php ^7.3.0 but your php version (8.0.3) does not satisfy that requirement.
```
Required version is from `7.3.0` till **(but not included)** `8.*`.

Yours PHP version is `8.0.3`

Next is problem number 2:
```
Problem 2
- intervention/image is locked to version 2.5.1 and an update of this package was not requested.
- intervention/image 2.5.1 requires ext-fileinfo * -> it is missing from your system. Install or enable PHP's fileinfo extension.
```

`intervention/image` requires `ext-fileinfo` PHP extension, so you would need to install it. Or you may have it installed, just uncomment `extension=php_fileinfo.dll` in your `php.ini` config file.

**Comment by nasirkhan** [comment]
are you sure that you are using the latest version? 

In the composer.json (https://github.com/nasirkhan/laravel-starter/blob/master/composer.json#L9) PHP7.3 and PHP8.0 both are supported. let me check again and i will confirm you after that.

**Comment by nasirkhan** [comment]
I just installed the project on Windows 11, XAMPP 8.0.9 and did get any of the issues. 

rather using the `composer install` command i would suggest to use `composer update` and you may not face the issue then.
