### ISSUE TITLE
Error when migrating

### ISSUE THREAD

**Issue by JohnB17** [nasirkhan/laravel-starter#292]
When seeding the database, one of them gave this error
![image](https://user-images.githubusercontent.com/63297273/142081042-1afa8d88-0b13-43f2-992c-e3b45c63177c.png)

**Comment by nasirkhan** [comment]
Can you please check that the version of MariaDb you are using supports JSON column?

**Comment by finnie2006** [comment]
I have the same problem, i run mariadb 10.5.13

**Comment by finnie2006** [comment]
@nasirkhan

**Comment by nasirkhan** [comment]
I assume the issue is with the MariaDb version.
Can you please check if you are using the latest version of MySQL or
MariaDb and the JSON column is supported there.

I use this starter for my own projects as well and I did not face such
issues.

--
*Nasir Khan Saikat*
www.nasirkhn.com

**Comment by finnie2006** [comment]
With mysql it works not with the latest mariadb

**Comment by nasirkhan** [comment]
Well, then I think you may need to update the MariaDb version. MariaDb do
supports the JSON column in some other latest versions. But if you are
using an older version then it might not work as expected.

--
*Nasir Khan Saikat*
www.nasirkhn.com

**Comment by finnie2006** [comment]
10.5.13 is the latest

**Comment by nasirkhan** [comment]
I pushed an update and you should install without any issues now.

--
*Nasir Khan Saikat*
www.nasirkhn.com

**Comment by JohnB17** [comment]
Fixed. Although, for some reason when I set something in the settings, it doesn't apply. It remembers what I set it to, but it doesn't change anything.

**Comment by nasirkhan** [comment]
@JohnB17 well you may need to clear the cache to see the changed data. As the Settings Items usually not changed that frequently, so they are cached for a longer time.

**Comment by finnie2006** [comment]
oh oki, also i tried oauth github but i get the following error when clicking on the button 

```
SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'name' cannot be null (SQL: insert into `users` (`first_name`, `last_name`, `name`, `email`, `updated_at`, `created_at`) values (, , ?, myemail@hotmail.com, 2021-11-20 17:19:18, 2021-11-20 17:19:18)) 
```

**Comment by nasirkhan** [comment]
I can see from the query that the First name and Last name is empty so the Name is empty. I always found that Github returns name and email while social login. You may have not set your name on your github account. Please Check the social login with an account with a name. 

If you want to allow User accounts without a first name or last name you need to implement that by your own. Or you can handle this exception and show a input form if the social account does not return a Name. If you can build a solution to address this issue, please consider submitting a PR to this repo.
