### ISSUE TITLE
Trying to get property 'bio' of non-object 

### ISSUE THREAD

**Issue by MusheAbdulHakim** [nasirkhan/laravel-starter#295]
When a user create an account that email is not verified and try to visit the profile page at the frontend, you get this error.
Also i have realize that, you are using the ids of the users in the profile page to get their information on the page. So i tried changing the values of the ids in the url and i was actually able to get the information of those users that existed in the database. This could be a security issue.

### Creating default object from empty value
I also the above error when updating  user info or when deleting to trash in the backend section.

**Comment by MusheAbdulHakim** [comment]
Even after the emailed is verified, it still give me this error.

**Comment by nasirkhan** [comment]
Thank you for reporting the issue. 

Unfortunately I could not reproduce the issue you mentioned. But from the subject of the issue I think for some reason your profile has not been created while creating new user. 'bio' is part of the 'userprofiles' table. Userprofile has an one to one relation with user. User profile page data are shown from the userprofiles table and if there is no entry found it may throw this type of error. Can you please check and confirm the number of rows in users and userprofiles are same in your application? 

Id of an user is being used to show their profile. I think is a very common practice and here only some specific non sensitive data are shown. There are a number of  other approaches can be taken but what you suggest? 

I could not reproduce the user delete issue as well, can you please look into your error log and you may share here as well.

**Comment by MusheAbdulHakim** [comment]
the users table and the userprofiles table do not have the same rows.But i suggest you make the bio column nullable since it is not in the register page.
This is my log file.
[laravel-2021-12-14.log](https://github.com/nasirkhan/laravel-starter/files/7712549/laravel-2021-12-14.log)

**Comment by metacraft-hq** [comment]
ErrorException
Attempt to read property "bio" on null. 

Fresh install localhost.. followed your git instructions.. How do i solve this please?

**Comment by nasirkhan** [comment]
Hi @AiFxApp , 

Did you followed all the steps to install? You will need to seed the database to access the backend and some other features. 

Please check the steps from here: https://github.com/nasirkhan/laravel-starter/wiki/Installation
