### ISSUE TITLE
Limits of license

### ISSUE THREAD

**Issue by codefixerZ** [nasirkhan/laravel-starter#298]
Thank you for your contribution. Can I use this project to make my system and sell it

**Comment by nasirkhan** [comment]
You can use this template project and build your product/project upon it. For both commercial and noncommercial use, you should mention the name of the original author and a link back to this repo. As you are planning to extend the project, it would be really helpful if you can submit Pull Requests to fix/ improve this project.

You can check the licence of the project to know more about the usages.
https://github.com/nasirkhan/laravel-starter/blob/master/LICENSE.md
