### ISSUE TITLE
Unsupported cipher

### ISSUE THREAD

**Issue by vallerydelexy** [nasirkhan/laravel-starter#302]
RuntimeException
Unsupported cipher or incorrect key length. Supported ciphers are: aes-128-cbc, aes-256-cbc, aes-128-gcm, aes-256-gcm.
http://localhost:8000/
![image](https://user-images.githubusercontent.com/17786532/149525273-a9d9cd05-e0c9-45e3-b859-f995d922e6c8.png)

**Comment by catwhocode** [comment]
Based on Laravel issue [here](https://github.com/laravel/framework/issues/9080) you can do one or more of these step(s)

`php artisan key:generate`
`php artisan config:clear`

open `config/app.php`
change from 

`'key' => env('32charshere'),` 

to 

`'key' => '32charshere',`
