### ISSUE TITLE
Register New User - - "last_login" on null - -

### ISSUE THREAD

**Issue by metacraft-hq** [nasirkhan/laravel-starter#323]
Error
Attempt to assign property "last_login" on null
http://127.0.0.1:8000/register

Fresh Install, followed your git instructions. 

Registered a new user and get error message. 

![image](https://user-images.githubusercontent.com/89227642/163042661-f4a0aaae-04ed-47d2-b1c3-0f1e72e1edee.png)

Please help me solve this -- your project is just awesome and want to dig in.

**Comment by nasirkhan** [comment]
Just published a new version with Laravel 9, can you please try that and let me know if the issue exists. 

I could not reproduce the issue,  I tried both from backend and frontend. Can you please tell which steps you followed to register the user?

After registration a `userprofile` is being created via an event, I think your event listener setting is not correct, did you checked the log?
