### ISSUE TITLE
RTL

### ISSUE THREAD

**Issue by omarmm** [nasirkhan/laravel-starter#326]
Hello 
Excuse me , how to apply RTL template , when I added 'ar' locale , time and date turns to arabic , but template still  LTR
Thank you :)

**Comment by nasirkhan** [comment]
Thanks for trying the Laravel Started project. 

There is no straight RTL conversion system available. But the theme used in Backend (CoreUI) and Frontned (Tailwind) both supports RTL. 
As i can not read any RTL languages, I could not implement that properly. As you are trying to use Arabic, you may add the RTL css (available in the theme doc) and submit a pull request here.

**Comment by omarmm** [comment]
@nasirkhan 
Hello brother , thank you very much for replying, I'll check  theme docs and if  everything go well  , sure I'll submit a PR 
thanks.

**Comment by nasirkhan** [comment]
Did you find any solution for RTL themes?

**Comment by omarmm** [comment]
> Did you find any solution for RTL themes?

Yes for( CoreUI ) .. it works perfect when you add  lang="ar" and dir="rtl" attributes to `<html>` tag in app.blade.php
I had tried same solution for (Tailwind) as they also mentioned in their documents .. but some   styles like sub menu items still not converted .

**Comment by nasirkhan** [comment]
Main menu and sub menu items did not had the translation strings. I updated a while ago and you may check that. 

I do not know how extensively you are translating the application, but there are a number of popular packages to manage translation, you can check those as well.
