### ISSUE TITLE
File manager allows arbitrary file upload.

### ISSUE THREAD

**Issue by BurakBoz** [nasirkhan/laravel-starter#337]
File manager is not configured by default. 
It allows uploading .php file extensions.
Also it allows .zip files upload and extraction. 

I've managed upload a web shell via direct shell.php upload and also shell.zip -> unzip method.

Consider strict rules against file extensions.

**Comment by nasirkhan** [comment]
Thanks for your feedback. I will look into the issue and will upload a fix.
