### ISSUE TITLE
feature image issue

### ISSUE THREAD

**Issue by azhar62355** [nasirkhan/laravel-starter#340]
![9ac7b8c6-a08b-481e-b059-1bc62e291074](https://user-images.githubusercontent.com/108658167/177110841-ac07bc42-a63d-443b-9b21-3199397e8225.png)
![ffbc9ef6-f518-4a1a-aaba-11758e1c01d5](https://user-images.githubusercontent.com/108658167/177110847-d289cfa0-c03b-4162-aeea-88b30108b529.png)
whenever i upload feature image in backend but in frontend feature image  is not came there is an issue in storage links in this project . if anybody haave any idea about this issur please reply

**Comment by nasirkhan** [comment]
A discussion is going on at https://github.com/nasirkhan/laravel-starter/discussions/341
