### ISSUE TITLE
Duplicating existing module "403 This action is unauthorized."

### ISSUE THREAD

**Issue by mewcrazy** [nasirkhan/laravel-starter#353]
Hi,
first let me say that you did amazing work here. Your starter got me into Laravel developing.

I'm having troubles duplicating the existing "Comments" module though. I copied the whole module directory and changed all Comments to a different name. So far so good. The module runs so far including all views. But when I do this "Authorizable" throws me a "403 This action is unauthorized" error.

Can you give me a hint how to authorize the new Controller/Action?

I can disable the error when I comment line 21 in your Controller. (use Authorizable;)

Regards,
Dennis

**Comment by nasirkhan** [comment]
Hi @mewcrazy , 

Feeling great to hear that you are using `Laravel Starter` for your own projects. 

I assume you got the error `403 This action is unauthorized` for the users other than the `super admin` role. Please read the wiki page https://github.com/nasirkhan/laravel-starter/wiki/Role-Permission and I hope you will find your answer there. You have to add new permissions and update the related roles as well. 

Please let me know if the wiki page cannot solve your issue.

thanks again, and please do consider contributing back to this project is possible!

**Comment by mewcrazy** [comment]
Hi,
indeed. It worked instantly as logged in Super Admin.

Thanks for the help!
