### ISSUE TITLE
Convert Mix to Vite [help]

### ISSUE THREAD

**Issue by ngaolun** [nasirkhan/laravel-starter#362]
To Nasirkhan, thanks for your code. I'm glad to use your starter kit. I want to convert mix to vite but i don't know how, i've searched some tutorials on internet but i'm not successful. Can't you help me. Thanks

**Comment by nasirkhan** [comment]
I am sorry that I can not help you now to convert mix to vite. 
To convert Laravel starter, it will take a decent amout of time and I do not have that right now. Laravel official doc is good enough to convert successfully.
