### ISSUE TITLE
when i run this "php artisan module:make about"

### ISSUE THREAD

**Issue by techliferestore** [nasirkhan/laravel-starter#374]
Getting error 
  file_get_contents(/var/www/html/laravel-starter-9.16.0/vendor/nwidart/laravel-modules/src/Support/../Commands/stubs/webpack.stub): Failed to open stream: No such file or directory

  at vendor/nwidart/laravel-modules/src/Support/Stub.php:106
    102▕      * @return mixed|string
    103▕      */
    104▕     public function getContents()
    105▕     {
  ➜ 106▕         $contents = file_get_contents($this->getPath());
    107▕ 
    108▕         foreach ($this->replaces as $search => $replace) {
    109▕             $contents = str_replace('$' . strtoupper($search) . '$', $replace, $contents);
    110▕         }

      +22 vendor frames 
  23  artisan:37
      Illuminate\Foundation\Console\Kernel::handle()

**Comment by nasirkhan** [comment]
can you please write a little more details about the error? like on which page you got this error?

**Comment by sachinshrm501** [comment]
Hello We are unable to create a new module 
get this error 
file_get_contents(/var/www/html/laravel-starter-9.16.0/vendor/nwidart/laravel-modules/src/Support/../Commands/stubs/webpack.stub): Failed to open stream: No such file or directory

**Comment by techliferestore** [comment]
Thanks for creating laravel starting web app or thank for replying
.Actually when i am using your new version i experience so much bugs and
issues your artisan command not running propery i also post a error on
issues...this issue
Like when i try to make a new module get this error missing webpackstub ,
Try to migrate demo data also I get error name is null in ,I cant able to
run
These error come after updated version 19.xx request you to kindly solve
this issue.....
I also have old version of yours i dont show any error but after updating
geting much error try to run artisan command you will find .....

**Comment by nasirkhan** [comment]
Thank you for using Laravel Starter. 

I assume, you are not following the installation steps. Can you please try to follow the instructions mentioned hare and let me know in which step you are getting the errors. 

https://github.com/nasirkhan/laravel-starter/wiki/Installation
