### ISSUE TITLE
While creating new Module it always create a new folder with name like "Module\{modulename}"

### ISSUE THREAD

**Issue by tarangpatel61** [nasirkhan/laravel-starter#378]

**Comment by tarangpatel61** [comment]
So it will not load the Module correctly in Laravel. 

Please Update the line By changing this in (vendor/nasirkhan/module-manager/src/Commands/ModuleBuildCommand.php);

![Screen Shot 2023-01-05 at 4 17 20 pm](https://user-images.githubusercontent.com/35031138/210710518-5ff525ad-b9f8-4ddb-95f8-ec4dc129771c.png)
Thanks

**Comment by chirumist** [comment]
go to composer.json and  change
change your module-manager package version 0.3.0 to 0.4.0 
https://github.com/nasirkhan/module-manager

**Comment by nasirkhan** [comment]
@chirumist thanks.
