### ISSUE TITLE
[Stubs] How to create full Module using laravel-starter-stubs

### ISSUE THREAD

**Issue by ghost** [nasirkhan/laravel-starter#380]
Hello!

I cannot generate a Module properly because it does not use stubs from laravel-starter-stubs directory. Currently, there is one Controller in Modules/Blog/Http/Controllers in the new installation. But there are Controllers in the new installation in Modules/Blog/Http/Controllers/Backend as well as Modules/Blog/Http/Controllers/Frontend. So my question is: How to force a generation of a Module using stubs having seperate Frontend and Backend  in different directories?

**Comment by nasirkhan** [comment]
Can you please elaborate the issue you are referring to?



Nasir Khan Saikat
https://nasirkhn.com

**Comment by DeRaja** [comment]
Hello!

Thanking you very much for your response. I am so delighted to have found such a wonderful work of yours. I was trying to integrate some things but foudn out that your work is kilometers ahead and, beyond that, very advanced. Thanking you for such a marvellous work.

Let me elaborate it again, my be my description of the issue above was not enough. I have two installations of Laravel starter, old (before two weeks) and new, with the latest version.

In the OLD INSTALLATION installed end of December 2022, I have the following:

```
Modules/Blog/Http/Controllers/Blog/Backend/BlogsController.php
Modules/Blog/Http/Controllers/Blog/Frontend/BlogsController.php
```

In the NEW (second) INSTALLATION of Laravel starter installed in January 2023, I have only one Controller without /Backend and without /Frontend:

`Modules/Blog/Http/Controllers/Blog/BlogsController.php`

This shows the new installation is not using stubs from laravel-starter-stubs to generate a new Module.

The new Module Blog DOES NOT APPEAR in the backend of admin.

Many files are missing in the new installation. In following messages I will give you detailed comparasion of old and new files in both installations.

**Comment by DeRaja** [comment]
In the OLD INSTALLATION installed end of December 2022, I have the following:

Modules\Blog\database\seeders\BlogDatabaseSeeder.php

```

namespace Modules\Blog\database\seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Modules\Tag\Entities\Blog;

class BlogDatabaseSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // Disable foreign key checks!
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');

        /*
         * Blogs Seed
         * ------------------
         */

        // DB::table('blogs')->truncate();
        // echo "Truncate: blogs \n";

        Blog::factory()->count(20)->create();
        $rows = Blog::all();
        echo " Insert: blogs \n\n";

        // Enable foreign key checks!
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');
    }
}
```

**Comment by DeRaja** [comment]
In the NEW (second) INSTALLATION of Laravel starter installed in January 2023, I have:

Modules\Blog\Database\Seeders\BlogDatabaseSeeder.php

```
namespace Modules\Blog\Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Database\Eloquent\Model;

class BlogDatabaseSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Model::unguard();
        // $this->call("OthersTableSeeder");
    }
}
```

**Comment by DeRaja** [comment]
In the OLD INSTALLATION installed end of December 2022, I have the following:

```
Console/Commands/BlogCommand.php
Database/fatories/BlogFactory.php
Database/migrations/***_create_blogs_table.php
Modules/Blog/Http/Controllers/Blog/Backend/BlogsController.php
Modules/Blog/Http/Controllers/Blog/Frontend/BlogsController.php
Http/middleware/GenerateMenus.php
lang/en/text.php
Models/Blog/Blog.php
Modules/Blog/Resources/views/backend/blogs/--->Bladefiles
(create, edit, form, show, trash, etc.)
Modules/Blog/Resources/views/frontend/blogs/--->Bladefiles
(index/show)
```

**In the NEW (second) INSTALLATION of Laravel starter installed in January 2023, I do not have above files.**

**Comment by DeRaja** [comment]
I get during installation following error message:

```
file_get_contents(/xxx/public_html/vendor/nwidart/laravel-modules/src/Support/../Commands/stubs/controller_backend.stub): Failed to open stream: No such file or directory

  at vendor/nwidart/laravel-modules/src/Support/Stub.php:106
    102▕      * @return mixed|string
    103▕      */
    104▕     public function getContents()
    105▕     {
  ➜ 106▕         $contents = file_get_contents($this->getPath());
    107▕
    108▕         foreach ($this->replaces as $search => $replace) {
    109▕             $contents = str_replace('$' . strtoupper($search) . '$', $replace, $contents);
    110▕         }

      +22 vendor frames
  23  artisan:37
      Illuminate\Foundation\Console\Kernel::handle()

```

**Comment by DeRaja** [comment]
In the config/modules.php I have now:```


    'stubs' => [
        'enabled' => true,
        // 'path' => base_path('vendor/nwidart/laravel-modules/src/Commands/stubs'),
        'path' => base_path('stubs/module-stubs'),        'files' => [
            'routes/web' => 'Routes/web.php',
            'routes/api' => 'Routes/api.php',
```

**Comment by DeRaja** [comment]
Now I changed in config/modules.php:

```
    'stubs' => [
        'enabled' => false,
```

There is no change. The error is the same that it cannot find Backend stub.

**Comment by ghost** [comment]
Hello nasir!

Vow! I found my mistake.I had wrongly used:

php artisan module:**make** Blog

Now, I used:

php artisan module:**build** Blog

This is a learning lesson for everyone in the future:
**There is difference in using generation commands with module:make and module:build. They will create Modules with different stubs.**

So I will close this issue.

**Comment by nasirkhan** [comment]
@DeRaja thank you for finding the solution by yourself. 

Actually I have plans to build a new module manager and remove the previous one. But unfortunately I could not manage enough time to build a complete module manager package, rather build a partial one. The new package helps to generate new modules with similar structure with the existing modules. I hope I will be able to complete the new package soon. 

If you are interested, you may contribute to Laravel Starter and the new package as well.

**Comment by ghost** [comment]
Hello Nasir!

> If you are interested, you may contribute to Laravel Starter and the new package as well.

Yes, I will contribute. But it will be limited as a tester and (indepth) reporter. I am not a php coder.

But if you want me to write docs in english and add it to this project, I can.

> Actually I have plans to build a new module manager and remove the previous one. But unfortunately I could not manage enough time to build a complete module manager package, rather build a partial one. 

What all you have achieved is already gigantic. If that remains as it is, that is fine. But there are other so many areas that also requires more basic features 

They are also be very fundamental and extremely necessary for a starter.
Here is my suggestion, although a bit off topic:
1)
One could be theme manager. Multiple thems could be mapped to multiple modules or domains from the admin. The views in every module are there. 
But that mapping in admin is missing.
2)
Second could be a domain manager for multisite. 
Multisite is a _MUST_ in this project and this could be made available from admin itself. One of the best package on multisite of all other open source, as I have analysed from many aspects is:

https://github.com/gecche/laravel-multidomain

If this could be tightly integrated, that would be beautiful. 
NB: I am not looking for any direct or indirect help in this direction. I am developing my own concept.
3)
Third is a Language Switcher in the frontend Blade templates as default. 
This is a starter thing and every starter will require, if the installation is language sensitive.
4)
Frondend Menu configurator, to be done from Backend.

There are a few more but above four are very basic things that every starter (like me) will require.

Anyway, I am too happy to use your valuable and amazing work and will support it in the way I can.

Thanks again.

**Comment by nasirkhan** [comment]
@DeRaja Thanks for your feedback 

New feature suggestions are really helpful. I was listing some of the future plans in https://github.com/nasirkhan/laravel-starter/issues/269 . I added your suggestions there. 

1. Theme manage: I also planned to do this, but could not complete it yet. 
2. Multisite: This is a basic starter, I think multi site/ multi tenant is an advance feature. though i added this on the future plan
3. Language Switcher: It is already implemented. You can access this from the backend. There is not much text available and did not implemented there. But as it is available in the core, you just have to use the `@lang` in the blade files. 
4. Visual Menu Manager: I also think it is a useful feature, but again not developed yet.
