### ISSUE TITLE
User profiles not created during installation

### ISSUE THREAD

**Issue by rabol** [nasirkhan/laravel-starter#381]
The user profiles is never created.

During installation, users are created, but the UserProfile record is nor created - e.g. the listener does not pick up the 'created' event when doing db seed

**Comment by nasirkhan** [comment]
This should not happen! did you checked the error log? have you followed the installation instructions as it is mentioned in the Readme file?

**Comment by rabol** [comment]
I think I have followed the instructions - I’ll double check -  the event in the seeder is not working, meaning that when one is doing ```php artiisan migrate —seed```` then the listener is not working

**Comment by rabol** [comment]
the UserCreated event is not fired when doing db seed

**Comment by nasirkhan** [comment]
I tested in my local and other server as well and event was firing every time. Have you seen any error while running the migration --seed?
