### ISSUE TITLE
SQLSTATE[42S02]: New table name password_reset_tokens

### ISSUE THREAD

**Issue by ghost** [nasirkhan/laravel-starter#390]
Hello!

For resetting the password, I get following error:

SQLSTATE[42S02]: Base table or view not found: 1146 Table 'db_nasir.password_reset_tokens' doesn't exist (Connection: mysql, SQL .....

Controller
    App\Http\Controllers\Auth\PasswordResetLinkController@store
Route name
    password.email
Middleware
        web

The table password_reset is there. 
But the table password_reset_tokens is not created.

Any solution for this?

**Comment by ghost** [comment]
Hello Nasir!

Ok, I found the problem. You have changed and given a new name of the table password_reset_tokens from password_reset. But you did not have the following file deleted and did not give a new file name:

2014_10_12_100000_create_password_resets_table.php

Because the some migration files does not work on MariaDB, I had kept the old file because I needed to enter:

$table->id('id');

Hence, the old table remained and new was'nt created.

After I went through all your commits, I could find this, have re-created everything and it works. If it is not a lot of work, it would help if you could make a new file:

2023_xx_xx_xxxxxx_create_password_resets_token_table.php

Please close this after you have read this issue.

**Comment by nasirkhan** [comment]
thanks for using the Laravel Starter and testing the new version. 

About this new table name, i followed laravel default changes. It did not create new migration rather renamed the old migration. So I did the same. For the new uses of this Starter,
