### ISSUE TITLE
jQuery errors in backend

### ISSUE THREAD

**Issue by SaJeTek-Developer** [nasirkhan/laravel-starter#393]
I just pulled a fresh copy of v10, followed your install instructions and ran "npm install" and "npm run build" (which should be included in the instructions)
When I log into the backend, i'm getting some errors in the console.

Data isn't loading even though the demo data is in the database.
![image](https://user-images.githubusercontent.com/8119344/225490423-6155b69c-f54a-4700-92a5-9c6b88fa6495.png)

**Comment by nasirkhan** [comment]
Thanks for reporting the issue. It has been resolved.
