### ISSUE TITLE
Uncaught ReferenceError: coreui is not defined

### ISSUE THREAD

**Issue by aiens** [nasirkhan/laravel-starter#394]
I just pulled a fresh copy of laravel-starter
When I log into the backend, i'm getting some errors in the console.

Uncaught ReferenceError: coreui is not defined

![image](https://user-images.githubusercontent.com/1411651/225831125-0c48a9a5-a8fb-4659-8789-6db485595a30.png)

**Comment by nasirkhan** [comment]
Fixed the issue. Thank you for using Laravel Starter and reporting the issue.
