### ISSUE TITLE
User Profile Not restored when restoring user

### ISSUE THREAD

**Issue by SaJeTek-Developer** [nasirkhan/laravel-starter#398]
The User Profile is Not restored when restoring a deleted user.

In the app/Http/Controllers/Backend/UserController.php

You have to add another line after `$$module_name_singular->restore();`

`$$module_name_singular->profile()->restore();`

**Comment by nasirkhan** [comment]
Thanks for reporting the issue and mentioning the solution. 

You may also submit pull requests to fix the issue and update new features as well.
