### ISSUE TITLE
multilanguage fronetend

### ISSUE THREAD

**Issue by stormtr** [nasirkhan/laravel-starter#408]
hi for this project on frontend section multilanguage must be in the prefix like www.blabla.com/en/about 
can you implement it to your system?

**Comment by nasirkhan** [comment]
`Laravel Starter` implemented the default approach of the Laravel localization (https://laravel.com/docs/localization). So you may change what else can be done here. 

In general I can say it it can be done. But implementing you custom requirement is out of scope of this project. I hope you will understand.
