### ISSUE TITLE
Image Manager not working

### ISSUE THREAD

**Issue by shozabjaveed** [nasirkhan/laravel-starter#411]
File /Image Manager not working

**Comment by nasirkhan** [comment]
Similar as https://github.com/nasirkhan/laravel-starter/discussions/410

**Comment by nasirkhan** [comment]
https://github.com/alexusmai/laravel-file-manager/issues/348

Reported the issue to package repo did not get any update yet.

**Comment by nasirkhan** [comment]
This issue has been resolved in the latest version of Laravel Starter.
