### ISSUE TITLE
[BUG + FIX] Recognize table prefix in Models

### ISSUE THREAD

**Issue by ghost** [nasirkhan/laravel-starter#412]
Hello Nasir!

I found a bug in the following

app/Models/BaseModel.php
```

    public function getTableColumns()
    {
        $columns = DB::select('SHOW COLUMNS FROM '.$this->getTable());
        return $columns;
    }
```

The above does not recognize table prefix.

Please change to the following code fix:

```
    public function getTableColumns()
    {
        $table = DB::getTablePrefix() . $this->getTable();
        $columns = DB::select('SHOW COLUMNS FROM '. $table);
        return $columns;
    }
```

I have not checked in other areas of your marvellous project, if this bug may cause a problem and also needs to be modified.

May I also take this opportunity to thank you for all the meticulous efforts in this project. This is really one of the best one I know.

**Comment by ghost** [comment]
I forgot.

It is also the time to change support of Laravel 9 to Laravel 10 everywhere, in particular also in the description of this wonderful project.

I also recommend to create a new tab to this project with "Laravel10" to make it searchable under this tag with a focus of Laravel 10 projects only.

**Comment by ghost** [comment]
Hello Nasir!

This fix should be applied to app/Models/Notification.php as well as in the backend to following files:

/resources/views/backend/includes/show.blade.php
/resources/views/backend/users/show.blade.php

**Comment by nasirkhan** [comment]
thanks for your suggestion. I will try to accommodate those soon.

**Comment by nasirkhan** [comment]
Fixed in recent release, thanks again.
