### ISSUE TITLE
load image in post edit  [BUG]

### ISSUE THREAD

**Issue by mybigopenbox** [nasirkhan/laravel-starter#416]
How to find
go to admin dashboard
from the list choose action -> edit
On Featured Image * Browser button on the right hand side doesn't appear to work

In Resources/views/backend/posts/form.blade.php  line 80 is defined as html->text()

however, it should be html()->input("file",

**Comment by nasirkhan** [comment]
Duplicate of #411 

`html->text()` is not a mistake. We are storing the file path via that field.

**Comment by mybigopenbox** [comment]
Hi Nasir

May you misunderstand, or I misunderstand you.
The browser button to the right of the text field labelled 'Featured Image'
When you click on it their is not pop-up window. Normally, clicking on a browser button the file upload model would pop up to allow you to select a file.. However, in this instance, and  am running off the main branch the file upload module does not pop up. I have even tried your online demo at https://laravel.nasirkhn.com/admin/posts/34/edit and it does pop up

So, may I ask, when you click on the button what is supposed to happen, and how does this field therefore get populated by the user to wants to select an image to upload.
If it is a text field, this is a manual field, and a user would not normally type it in but select from a file upload model

Can you provide more detail

Thanks

**Comment by nasirkhan** [comment]
Can you please download and install the latest version and check if it is working now or not?

**Comment by mybigopenbox** [comment]
Thanks.

Like the ability to load, preview, and create directory.

Very nice approach

**Comment by irvnh05** [comment]
The image won't display in the post, and I've tried php artisan storage:link

**Comment by nasirkhan** [comment]
> The image won't display in the post, and I've tried php artisan storage:link

This issue has been resolved and closed. Can you please create a new issue with a little more details, so that I can understand the problem you are facing here.
