### ISSUE TITLE
[Feature request] Choose a language from a multilanguage dropdown in the frontend

### ISSUE THREAD

**Issue by ghost** [nasirkhan/laravel-starter#421]
Hello Nasir!

Multilanguage is already implemented. 

It would help everyone, if there is a possibility to choose a language in the front end, for e.g. by a drop down or a link selector. 

As this is a starter project and if this feature is already there, which many can use, then why not offer a ready made solution? What do you think of this feature request?

**Comment by nasirkhan** [comment]
It is good to have. 

As you know multilanguage is already implemented. It is a starter project and someone else will work on it as needed and then publish/ release it. So it is up to that person who is working on it.

There are a number of places in Frontend where improvement is needed. This is one of them. 

I would really appreciate you if you may submit a PR implementing this feature.

**Comment by ghost** [comment]
Hello Nasir!
I installed the starter project for learning purpose and liked it. I found it can be developed further, as you rightly pointed out. I am not a coder. Never placed a PR. My coding knowledge is limited.

**Comment by nasirkhan** [comment]
Resolve in a recent release.
