### ISSUE TITLE
Sidebar Toggle Error

### ISSUE THREAD

**Issue by lutfiidham** [nasirkhan/laravel-starter#431]
Sidebar toggle not work, when I click "hamburger button", appear "coreui is not defined" on console.

![image](https://github.com/nasirkhan/laravel-starter/assets/21997116/6a086f01-552a-4372-aad6-75b99dd21632)

**Comment by nasirkhan** [comment]
thanks for reporting the issue. I will look into it and will try to fix it. 
If you know the solution, please submit a PR.

**Comment by lutfiidham** [comment]
thanks for your respond.
sorry I'm newbie on programming. This is my temporary solution, I just add coreui cdn on header.blade.php before `header` tag.

`<script src="https://cdn.jsdelivr.net/npm/@coreui/coreui@4.2.0/dist/js/coreui.bundle.min.js" integrity="sha384-n0qOYeB4ohUPebL1M9qb/hfYkTp4lvnZM6U6phkRofqsMzK29IdkBJPegsyfj/r4" crossorigin="anonymous"></script>`

Please fix use laravel way. Thank you, bro.

**Comment by Rafaelknz** [comment]
I tried using the solution mentioned by @lutfiidham, but that caused another problem in my sidebar because probably it duplicates some events, instances or listeners.

I solved this by creating an "client" instance of coreui in app-backend.js

`import * as coreui from '@coreui/coreui';`
`window.coreui = coreui;`

**Comment by nasirkhan** [comment]
Thanks @Rafaelknz. I think this solves the issue. I pushed a new release with this fix. 

> I tried using the solution mentioned by @lutfiidham, but that caused another problem in my sidebar because probably it duplicates some events, instances or listeners.
> 
> I solved this by creating an "client" instance of coreui in app-backend.js
> 
> `import * as coreui from '@coreui/coreui';` `window.coreui = coreui;`

**Comment by lutfiidham** [comment]
oh yeah, thank you so much @nasirkhan, @Rafaelknz
