### ISSUE TITLE
Adding a new dashboard design (in .blade format).

### ISSUE THREAD

**Issue by Fzoltan87** [nasirkhan/laravel-starter#433]
Dear Nasir Khan!

How do I change the design of my existing dashboard to a new design?
I want to use only Bootstrap 5 and Fontawesome on the frontend and backend side, I want to delete tailwindcss from the starting project. Thank you very much for your help.

**Comment by nasirkhan** [comment]
thank you for using Laravel Starter. 

Backend is using a Bootstrap 5-based theme, you may follow the process of implementing that and try to do the same for Frontend. 

You may find related doc online, but it is not possible for me to assist you with references and in details about removing Tailwind and use Bootstrap.

**Comment by Fzoltan87** [comment]
I thought I wanted to replace the coreui/coreui package with my own package.
Is it enough to delete this component from composer.json and package.json files?
Or should I also delete the resources/vendors/coreui folder?

**Comment by nasirkhan** [comment]
There are a number of approaches to using Bootstrap themes on Laravel Starter. The simplest approach could be removing Vite directives from the layout files and including a CDN or local CSS-JS.
