### ISSUE TITLE
Dashboard Design Outdated

### ISSUE THREAD

**Issue by Muhammad-Arsal** [nasirkhan/laravel-starter#458]
Well you have a great starter kit. But what seems to be the problem is that the design of the admin panel is a bit outdated type. Don't you think it should be replaced with the modern design

**Comment by nasirkhan** [comment]
Thank you for using Laravel Starter. 

Yes, backend theme is a little outdated and I really want to use a better theme. But I could not manage enough time to look into new themes for Laravel Starter.

You may suggest new theme options which are free and have good documentation.
