### ISSUE TITLE
Cannot add categories and tags when creating articles

### ISSUE THREAD

**Issue by jarwonozt** [nasirkhan/laravel-starter#460]
When I'm going to add an article, I can't enter categories and tags, why is that?
![Screenshot from 2023-08-04 01-38-22](https://github.com/nasirkhan/laravel-starter/assets/67833034/0bb60ea4-8817-4b66-bf1e-b0fba7320158)

**Comment by nasirkhan** [comment]
If you have created categories and tags, then you may select those from the Post creat/edit page.

**Comment by jarwonozt** [comment]
> If you have created categories and tags, then you may select those from the Post creat/edit page. 

I have created categories and tags, but when I will create a category selection article and the tag doesn't appear, I have to write in the select2 search field after that it just appears. does the bootstrap version affect? I checked on the web demo it still uses bootstrap 4 while in repo i I use bootstrap 5

**Comment by jarwonozt** [comment]
> If you have created categories and tags, then you may select those from the Post creat/edit page. 

I have created categories and tags, but when I will create a category selection article and the tag doesn't appear, I have to write in the select2 search field after that it just appears. does the bootstrap version affect? I checked on the web demo it still uses bootstrap 4 while in repo i I use bootstrap 5

**Comment by nasirkhan** [comment]
updated demo site and this repo as well. thanks.
