### ISSUE TITLE
adding searchpane

### ISSUE THREAD

**Issue by markplus** [nasirkhan/laravel-starter#463]
hello I wanted to know if adding searchpanes to your project is simple and can be done, I've been trying to do it with serviside for some time but I haven't succeeded yet even buying the datatables editor license, can you help me?

**Comment by nasirkhan** [comment]
I have not used this feature of Datatables. So I am not sure how this can be implemented. If you have found the solution, please let me know, I may add that in this project and you may submit a pull request as well.
