### ISSUE TITLE
How to access Menu generator?

### ISSUE THREAD

**Issue by cleargoal** [nasirkhan/laravel-starter#486]
Hello!
Thanks for your work! It's a great package!

Only one thing is unclear, how to rich to the Menu Generator?
Explain, please.

**Comment by nasirkhan** [comment]
I am really happy that you found this project useful. 

At present there is no general menu generator. If you create a new module an admin menu sidebar menu item will be added. 

For the core and the modules, there are middlewares named `GenerateMenus.php` to manage menus. 

I am searching for a good menu manager/ generator package. If you know any please share, I will try to test that and may add to this project if it meets the requirements.

**Comment by cleargoal** [comment]
Thanks for your response!
I understand the functionality of the menu generator, now.
Thank you!
I don't know any other packages, so I am satisfied with yours.

Best regards!
