### ISSUE TITLE
Class "PDO" not found

### ISSUE THREAD

**Issue by LazyOmJay** [nasirkhan/laravel-starter#490]
i got this error when i hosting my laravel,

Error
PHP 8.2.8
10.22.0
Class "PDO" not found

i've tried enabling PDO Extension on PHP but it does'nt work at all, can you help me?

![Untitled](https://github.com/nasirkhan/laravel-starter/assets/140497524/9a96f2a9-6d4e-47cc-ac67-97f50da19d10)

**Comment by nasirkhan** [comment]
Can you please write a little more about the issue? Like the operating system/ hosting platform? 

Can you install a fresh Laravel? Does it work properly?

**Comment by LazyOmJay** [comment]
> Can you please write a little more about the issue? Like the operating system/ hosting platform?
> 
> Can you install a fresh Laravel? Does it work properly?

Yes, im using CPanel and i can install fresh laravel from their Terminal, also Extension has already enabled

**Comment by LazyOmJay** [comment]
> Can you please write a little more about the issue? Like the operating system/ hosting platform?
> 
> Can you install a fresh Laravel? Does it work properly?

This is a few Screenshoot from my extension
![Screenshot (1)](https://github.com/nasirkhan/laravel-starter/assets/140497524/2265cff8-3ef8-4a03-9141-ea066c7a468c)

![Uploading Untitled.jpg…]()

**Comment by LazyOmJay** [comment]
Error

  Class "PDO" not found

  at vendor/laravel/framework/src/Illuminate/Database/Connection.php:120
    116▕      * The default fetch mode of the connection.
    117▕      *
    118▕      * @var int
    119▕      */
  ➜ 120▕     protected $fetchMode = PDO::FETCH_OBJ;
    121▕
    122▕     /**
    123▕      * The number of active transactions.
    124▕      *

      +15 vendor frames

  16  app/Providers/AppServiceProvider.php:22
      Illuminate\Support\Facades\Facade::__callStatic()
      +7 vendor frames

  24  [internal]:0
      Illuminate\Foundation\Application::Illuminate\Foundation\{closure}()

**Comment by nasirkhan** [comment]
If you can install a fresh laravel then you should see the same error there as well. Because your mentioned following code is a part of Laravel core. 

```
at vendor/laravel/framework/src/Illuminate/Database/Connection.php:120
```

To fix the issue, first setup a local development environment and try to run the project there first.

**Comment by LazyOmJay** [comment]
> If you can install a fresh laravel then you should see the same error there as well. Because your mentioned following code is a part of Laravel core.
> 
> ```
> at vendor/laravel/framework/src/Illuminate/Database/Connection.php:120
> ```
> 
> To fix the issue, first setup a local development environment and try to run the project there first.

So what i need to do now is, setting up my project on my local computer, and then check either its working or not?

thanks i will do this First

Edit : It's Workingly fine on my local computer, it's only happen when i upload it to hosting

Screenshoot :
![Screenshot (2)](https://github.com/nasirkhan/laravel-starter/assets/140497524/10adc8b4-74cf-4fa8-ac0f-219973368c02)


Fresh Laravel :
![Screenshot (3)](https://github.com/nasirkhan/laravel-starter/assets/140497524/67b20f9c-411b-4ead-9c45-a0bbeed13e26)

**Comment by nasirkhan** [comment]
As it is working on your local then you know your application is working as expected. 

You may upload the application again. The latest Laravel Starter needs PHP8.1, be sure that you have enabled this version. If you see the precious error again, you should talk to the hosting provider for assistance.
