### ISSUE TITLE
General User can't to store post

### ISSUE THREAD

**Issue by cleargoal** [nasirkhan/laravel-starter#492]
I created a form for front users to give them the possibility of post creation. For this purpose, I copied blades and controllers from the backend and changed some lines of code to launch form for a general user.  Also, I added routes for form creation and store.
The form appears but doesn't send the query to the controller.

Are there any prohibitions in the code for users to create a post?

**Comment by nasirkhan** [comment]
Yes it is possible to open a form for general users to create a new post. 

Laravel Starter does not have the create route/method built in for the Frontend. It completely depends on your implementation. There might be many reasons for not being able to create a new post. You may follow the backend code or follow a different path.

**Comment by cleargoal** [comment]
I resolved this. Close this issue, please.
