### ISSUE TITLE
[Bug] Remove adding double db_prefix from InsertDemoData.php

### ISSUE THREAD

**Issue by ghost** [nasirkhan/laravel-starter#508]
Hello Nasir!

I tested that DB_PREFIX=master_ in .env is not effective. This would be helpful in many cases, when someone wants to use Multisite feature based on .env (for e.g. by gecche).

So, I used the database.php, I use a prefix, like this:

```
'connections' = 'mysql' =>

'prefix' => 'master_',
```

The following code in line 41 gives an error:

```
/home/.../public_html/app/Console/Commands/InsertDemoData.php

if ($fresh) {
    $this->truncate_tables();
}
```

The cause is the table prefix is added twice by DB::getTablePrefix(). Then, following will remove the error:

Line 141:
```
// $table_name = DB::getTablePrefix().''.$row;
$table_name = $row;
```

From the last attempt to install the Laravel Starter, I see that there are 200 stars more. This is excellent. 

But I also wonder why am I the first to use this demo feature. Hello Github users! Come on, please report such a bug here,  if you found one.

**Comment by nasirkhan** [comment]
fixed the issue. thanks for reporting.
