### ISSUE TITLE
[Bug] add ids ( for e.g. 'id' => '1', )  in the demo data when using MariaDB

### ISSUE THREAD

**Issue by ghost** [nasirkhan/laravel-starter#509]
Hello Nasir!

I changed to the following because the auth()->user()->name  is not available:

Modules/Article/Models/Post.php

```
    public function setCreatedByNameAttribute($value)
    {
        $this->attributes['created_by_name'] = trim(label_case($value));

        $author = "Author";

        if (empty($value)) {
            $this->attributes['created_by_name'] = $author; // auth()->user()->name;
        }
    }
```

**Comment by ghost** [comment]
Hello Nasir!

Something similar happens with Comment.php in the function setUserIdAttribute on line 82. May be you should revisit the insert demo on CLI, while having a DB prefix and check some bugs. Most likely you did not use a prefix and these bugs remained.

**Comment by ghost** [comment]
Hello Nasir!

I found the root cause of this problem.

In the UserTableSeeder, you did not use the ID. Now, I created one like this for all fake/default users:
```
        // Add the master administrator, user id of 1
        $users = [
            [
                'id' => '1',
```
I repeated the same for PermissionRoleTableSeeder like this:
```
        // Create Roles
        $super_admin = Role::create(['id' => '1','name' => 'super admin']);
        $admin = Role::create(['id' => '2','name' => 'administrator']);
        $manager = Role::create(['id' => '3','name' => 'manager']);
        $executive = Role::create(['id' => '4','name' => 'executive']);
        $user = Role::create(['id' => '5','name' => 'user']);
```
The same thing I did for UserRoleTableSeeder like this:
```
        User::findOrFail(1)->assignRole('super admin');
        User::findOrFail(2)->assignRole('administrator');
        User::findOrFail(3)->assignRole('manager');
        User::findOrFail(4)->assignRole('executive');
        User::findOrFail(5)->assignRole('user');
```
Then I was able to insert the Demo data.
The above bug got fired because in my database, all the ID for every record starts with the number 2 and it continues with the next record by adding 4. The next one is 4, 8, 12, 16, 20, 24, etc.

I do not know why this adding of 4 to each record id is hapenning. It looks like you use mysql and I use MariaDB (latest). So the creation process is different.

After finding this, I have removed the temporary tracking of this source of bug with $author = "Author";, as mentioned above. 

Thus, everything works fine after addition of correct id in the Seeders.

It is upto you to change it and modify the demo data. If not, please close this issue.

**Comment by nasirkhan** [comment]
fixed the issue. thanks for reporting.
