### ISSUE TITLE
Frontend page language dropdown menu bug

### ISSUE THREAD

**Issue by chzng** [nasirkhan/laravel-starter#522]
Frontend page language dropdown menu bug
![20231230224911](https://github.com/nasirkhan/laravel-starter/assets/9945287/2efcdac1-c853-491d-b7cb-411730043896)

**Comment by chzng** [comment]
### Fix the /livewire/livewire.js 404 not found error
https://livewire.laravel.com/docs/installation#manually-bundling-livewire-and-alpine

https://livewire.laravel.com/docs/installation#manually-bundling-livewire-and-alpine

**Comment by nasirkhan** [comment]
Can you please explain a little more about the issue you want to report here? does the dropdown menu open while you click on it?

**Comment by YZenKid** [comment]
![Screenshot_1](https://github.com/nasirkhan/laravel-starter/assets/60564470/9b4ce992-bcc3-4f04-a720-5c884f7db6cb)

Language selection dropdown always show in firstload and can't hide it.
