### ISSUE TITLE
Register option not showing

### ISSUE THREAD

**Issue by Omais-Rana** [nasirkhan/laravel-starter#528]
There's no sign up/new user registration option displaying anywhere. 
I have removed the user_registration() condition and now its showing. But there are errors when accessing user profile made using new registration or doing anything that requires authentication.

**Comment by Omais-Rana** [comment]
I have removed the userregistration() condition and now its working

**Comment by Omais-Rana** [comment]
The errors are being caused by date_of_birth and such parameters that cannot be set at User Registration. I erased those parts and now the profile module works. But still the @if user_registration() needs fixing

**Comment by nasirkhan** [comment]
Thanks for reporting the issue. 

It would be really helpful to fix this issue if you may share a screenshot with errors.
