### ISSUE TITLE
Demo site is broken

### ISSUE THREAD

**Issue by AllTheUserNamesAreGone** [nasirkhan/laravel-starter#531]
Just so you know. I was looking into the project and went to your demo site. There's internal server error 500 on the Comments and Posts (?) page. Also can't log in as admin and never get to see the user menu when logged in as the user. The pick a language menu never goes. Also can't log out because you can't see the user menu.

**Comment by nasirkhan** [comment]
Thanks for reporting. We are moving the demo server. We hope the issue will be resolved by next week.
