### ISSUE TITLE
Upgrade to Laravel 11

### ISSUE THREAD

**Issue by jarwonozt** [nasirkhan/laravel-starter#532]
I tried upgrading to Laravel 11 according to the Laravel documentation guide, but it still doesn't work with an error like the picture below.

![Screenshot from 2024-03-14 20-55-29](https://github.com/nasirkhan/laravel-starter/assets/67833034/da75407a-c4eb-463d-a8e3-721ab0d91d0d)

Do I have to wait for updates from this original repo ?

Error message :
```
Problem 1
      - Only one can be installed: illumination/contract[v5.0.0, ..., v5.8.36, v6.0.0, ..., v6.20.44, v7.0.0, ..., v7.30.6, v8 .0.0 , ..., v8.83.27, v9.0.0, ..., v9.52.16, v10.0.0, ..., v10.48.2, v11.0.0, ..., v11.0.5], laravel/ framework [v11.0.3, v11.0.4, v11.0.5]. laravel/framework replaces illumination/contracts and therefore cannot coexist with it.
      - arcanedev/support[10.0.0, ..., 10.0.1] requires illumination/contract ^10.0 -> can be satisfied with illumination/contract[v10.0.0, ..., v10.48.2].
      - arcanedev/log-viewer 10.0.0 requires arcanedev/support ^10.0 -> can be satisfied by arcanedev/support[10.0.0, 10.0.1].
      - Root composer.json requires arcanedev/log-viewer ^10.0 -> can be satisfied by arcanedev/log-viewer[10.0.0].
      - Root composer.json requires laravel/framework ^11.0.3 -> can be satisfied by laravel/framework[v11.0.3, v11.0.4, v11.0.5].

Use the --with-all-dependencies (-W) option to allow upgrading, downgrading, and removing packages currently locked to a specific version.
```

**Comment by nasirkhan** [comment]
Thank you for trying to update to Laravel 11. 

As the error suggests updates are blocked by the dependent 3rd party packages. I want to wait this week and then will update Laravel Starter. I hope related packages might be updated by then. If not I will use similar packages for the tasks.

**Comment by huylong** [comment]
@nasirkhan thank you so much.
