### ISSUE TITLE
Frontend and Backend Issues - Are Updates No Longer Being Applied?

### ISSUE THREAD

**Issue by JunYoungMoon** [nasirkhan/laravel-starter#539]
1. In routes/auth.php, we are fetching the USER_REGISTRATION value through user_registration(). However, even when this value is set to true in the env, it doesn't change $user_registration to true. Due to this issue, the register button in the header remains inactive for guest users.
![image](https://github.com/nasirkhan/laravel-starter/assets/35192352/9e7e2c0d-99da-4d0a-899b-be1a5356b041)

2. Tags like @click and @keydown.escape aren't functioning on all elements, preventing actions such as closing the language menu list in the header.
![image](https://github.com/nasirkhan/laravel-starter/assets/35192352/b6406c9f-bf2c-43d8-ac53-7feba2ef637d)

**Comment by nasirkhan** [comment]
Thanks for reporting the issue. 
Upgrading to Laravel 11 is in progress. I hope these issues will be fixed there. If you find a solution in between this time, please submit a PR.
