### ISSUE TITLE
There is a problem when uploading images，the LFMButton woking error

### ISSUE THREAD

**Issue by yunter** [nasirkhan/laravel-starter#580]
There is a problem when uploading images，the LFMButton woking error:
![WX20240503-221121@2x](https://github.com/nasirkhan/laravel-starter/assets/164930/24b26720-8841-46b1-ac2e-b6aa68380fdf)
Uncaught TypeError: Cannot read properties of undefined (reading 'top')
    at t.value (summernote-lite.min.js:2:148092)
    at HTMLButtonElement.handle (jquery-3.6.4.min.js:2:46636)
    at HTMLButtonElement.dispatch (jquery-3.6.4.min.js:2:43184)
    at y.handle (jquery-3.6.4.min.js:2:41168)
Maybe it's a compatibility issue

**To Reproduce**
1. Go to 'posts'
2. Click on 'create'
3. Mouse over summernote  LFMButton image icon got above error.
4. See attach file

**Expected behavior**
can show tooltip and none errors

**Screenshots**
See attach file.

**Additional Information**
V11.5 and V11.6

Install by composer create-project nasirkhan/laravel-starter

{
    "private": true,
    "type": "module",
    "scripts": {
        "dev": "vite",
        "build": "vite build"
    },
    "devDependencies": {
        "@coreui/coreui": "^5.0.0",
        "@fortawesome/fontawesome-free": "^6.5.1",
        "@popperjs/core": "^2.11.8",
        "@tailwindcss/forms": "^0.5.2",
        "alpinejs": "^3.4.2",
        "autoprefixer": "^10.4.2",
        "axios": "^1.6.4",
        "bootstrap": "^5.3.3",
        "flowbite": "^2.3.0",
        "jquery": "^3.7.1",
        "laravel-vite-plugin": "^1.0",
        "postcss": "^8.4.31",
        "sass": "^1.72.0",
        "sass-loader": "^14.1.1",
        "simplebar": "^6.2.5",
        "tailwindcss": "^3.1.0",
        "vite": "^5.2"
    }
}

**Comment by nasirkhan** [comment]
I found this issue as well, but the editor workes with this. Unfortunately, the 'summernote' has not been updated for a long time. I was thinking about using other WYSIWYG text editor.

It would be great if you may have a better solution, you may send pull request as well.

**Comment by yunter** [comment]
Is a problem with the Summernote-Lite version, so maybe Quill Rich Text Editor is an alternative.

**Comment by nasirkhan** [comment]
@yunter 
thanks for the update, does the `Quill Rich Text Editor` have file browser? or does it fits in with Laravel Starter?
