### ISSUE TITLE
dark mode

### ISSUE THREAD

**Issue by allotmentandy** [nasirkhan/laravel-starter#581]
i have installed the starter package and it  all works nicely

just dont see the dark mode option, is there anything i need to do install this? 

the screendumps have this in the header, by the language switcher, but i cant see any code for this in the /resources/views/frontend/includes/header.blade.php file.

has the dark mode functionality been removed? or do i need to do something to get it working?

**Comment by allotmentandy** [comment]
the problem was i installed it with php version 8.1, so go an older version

i upgraded to php 8.3 and it works with the newest branch.

**Comment by nasirkhan** [comment]
thanks 😄
