### ISSUE TITLE
Edit/Update, create new etc gives 500 server error

### ISSUE THREAD

**Issue by bipsdevs** [nasirkhan/laravel-starter#593]
Hi, I have installed Laravel Starter on my server. Everything seems fine except for editing/updating and creating new articles.
Update something on the setting page gives a 500 server error, creating a new article gives a 500 error. I tried your demo site too, there is also the same error. Please suggest

**Comment by nasirkhan** [comment]
Can you please be more specific about the error? like which page you wanted to edit/update, share any screenshot or the issue you are facing will be a great help

**Comment by bipsdevs** [comment]
![image](https://github.com/nasirkhan/laravel-starter/assets/135993083/63b4642d-6fb3-4dba-ad45-9716f9a9f538)
For e.g. the above error comes when I save/update the settings page. I am on PHP 8.3.7

**Comment by nasirkhan** [comment]
thanks for reporting the issue. a patch has been merged into the main branch.
