### ISSUE TITLE
Flashing page everytime click the menu

### ISSUE THREAD

**Issue by boedyirh** [nasirkhan/laravel-starter#607]
**Describe the bug**
Everytime I click menu, the website is flashing. My configuration is dark mode

**To Reproduce**
1. Click the menu.

**Expected behavior**
It should be change the website related to the menu clicked

**Screenshots**

**Additional Information**
I suspect it has something to do with placement of CSS and JS. The CSS is not loaded properly but the website already execute the page.
or perhaps, because I am using dark mode, The web go to the light mode first, and then apply the dark mode. and to my eyes seems there is flashing. 
But actually it is dark mode is being applied.

**Comment by nasirkhan** [comment]
will it be possible to share any screenrecord of the issue? You may use https://www.loom.com/screen-recorder and share a link

**Comment by boedyirh** [comment]
Here is the recorded screen
https://github.com/nasirkhan/laravel-starter/assets/10396931/f4dac815-b23f-441a-b484-de155796e569

**Comment by nasirkhan** [comment]
thanks for reporting the issue. Fixed the issue for front end. Will try to work on the backend, if you have already found the solution please submit a PR.

**Comment by boedyirh** [comment]
Thanks, it works perfectly.
faced problem before, but after clear cache. it works perfectly.
